### ISSUE TITLE
BUG: Unit test fails on x86 platform

### ISSUE THREAD

**Issue by rogers0** [seccomp/libseccomp-golang#24]
Debian version has an issue that unit test fails on x86:
> 	seccomp_test.go:455: Syscall should have returned error code!

checked the code:
  err = syscall.Setreuid(uid, euid)
and err seems to be nil, not the expected syscall.Errno(2)
On x64 (amd64) platoform, this cannot be reproduced.

See Debian BTS: https://bugs.debian.org/860618

**Comment by mheon** [comment]
This looks similar to a bug that was fixed in `libseccomp` v2.2.1. Are you building for Debian stable? If so, I believe you're still on a version of `libseccomp` early enough for that bug to appear... but then again, there are compile-time checks to make sure that specific combination cannot build.

I'll look into this more this afternoon.

**Comment by rogers0** [comment]
@mheon yes, for debian stretch, the next stable.
now stretch has been frozen, which means we can only patch current version, but cannot update to your latest release.
if you can provide a backport patch to fix the unit test issue on x86, it'd be appreciated!
thank you!

**Comment by mheon** [comment]
Stretch should be too new to see that specific bug, as it ships v2.3.1, so this is probably a bug in the bindings.

The Git snapshot you're using is a little old and missing most of the recent work that has gone in, so hopefully it's just a matter of applying one or two of those newer patches. There was a significant bugfix patch last week that might be related (06e7a29f36a34b8cf419aeb87b979ee508e58f9e in master), and hopefully applying that will resolve it. I'll spin up a test VM and check.

**Comment by rogers0** [comment]
@mheon thanks for your prompting response!

I tried cherry-pick 06e7a29, and build in git-pbuilder, the result is the same as before.
I guess maybe we need to cherry-pick more commits ...

**Comment by mheon** [comment]
Could be unrelated to that bug, then. It's interesting that it's 32-bit only. I begin to suspect it's the syscall being used in the test - maybe a behavior difference between 32 and 64 bit versions that glibc abstracts away but Go's standard library doesn't.

**Comment by mheon** [comment]
I have verified that this issue still exists in up-to-date master. I'll look into the cause now and see about getting it patched.

**Comment by mheon** [comment]
I've replicated the result in C (calling directly into `libseccomp` without using the `libseccomp-golang` bindings). This appears to be a bug in `libseccomp` itself. I'll file it upstream there.

**Comment by rogers0** [comment]
@mheon thanks for your info!

**Comment by rogers0** [comment]
@mheon reading the #84 issue of seccomp/libseccomp, though I'm quite sure, I feel this may be fixable without touching libseccomp. So is there a patch for golang bindings? Thank you!

**Comment by mheon** [comment]
@rogers0 Sorry for the delay on this one. You're correct, it looks to be an error in the test suite for the bindings. I have a test patch available at https://github.com/mheon/libseccomp-golang branch `test-failure-32bit`, commit b03f1efc22b3aaae017d9985efbc7a4c801951eb - can you verify this resolves the issue? If it does, I'll get it merged into master.

**Comment by rogers0** [comment]
@mheon Thanks for your patch!
I confirm it fixes the build on i386. I already make the debian release, and now is waiting for sponsor to upload to debian archive.
