### ISSUE TITLE
BUG: Unit test TestRuleAddAndLoad fails on armhf

### ISSUE THREAD

**Issue by rogers0** [seccomp/libseccomp-golang#25]
Debian version 0.0~git20150813.0.1b506fc-2 already applied https://github.com/seccomp/libseccomp-golang/commit/b03f1efc22b3aaae017d9985efbc7a4c801951eb, so issues on i386 got resolved. Thanks for help!

However, I find that version still fails on armhf:
  https://tests.reproducible-builds.org/debian/rbuild/testing/armhf/golang-github-seccomp-libseccomp-golang_0.0~git20150813.0.1b506fc-2.rbuild.log

related log is (hopefully):
=== RUN   TestRuleAddAndLoad
--- FAIL: TestRuleAddAndLoad (0.00s)
	seccomp_test.go:453: Error loading filter: invalid argument
	seccomp_test.go:459: Syscall should have returned error code!
	seccomp_test.go:465: Syscall should have returned error code!
FAIL
exit status 1

If you want to compare the build log on i386, it's here:
  https://tests.reproducible-builds.org/debian/rbuild/testing/i386/golang-github-seccomp-libseccomp-golang_0.0~git20150813.0.1b506fc-2.rbuild.log

Thank you!

**Comment by mheon** [comment]
I suspect that this is just another error in the test suite, though the EINVAL on filter load is interesting and different from what was happening before. I'll give it a look on Monday.

**Comment by mheon** [comment]
Sorry for the delay on this one, had issues getting a working ARM environment. I can't reproduce on Debian Testing RC3 armhf. I've tried both master, and the tree you're using (1b506fc plus b03f1ef). It looks like it could be an environment issue of some sort. Is there a collection of details on how the builders Debian uses are configured?

**Comment by rogers0** [comment]
@mheon I don't have armhf box, so I cannot confirm commands below.
(but it confirmed to occur on reproducible build and DoM building environment)
based on my experience of other golang packages in Debian, build command is like:

```shell
# below: if you didn't do this before
sudo apt install git-buildpackage pristine-tar equivs
gbp clone --pristine-tar https://anonscm.debian.org/git/pkg-go/packages/golang-github-seccomp-libseccomp-golang.git
cd golang-github-seccomp-libseccomp-golang
# you should on branch master

# below: install build dependencies
mk-build-deps --root-cmd sudo --install --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends"

# below: routine building work
gbp buildpackage --git-pristine-tar
```

**Comment by rogers0** [comment]
latest debian version 0.9.0-1 rebuild well one all platforms, including armhf:
- https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/golang-github-seccomp-libseccomp-golang.html

So I close this ticket.
Thank you!
