### ISSUE TITLE
BUG: "AUDIT_ARCH_MIPSEL64" undeclared here (not in a function)

### ISSUE THREAD

**Issue by guoh1988** [seccomp/libseccomp-golang#30]
os:linux arch:mips golang :1.7.5
1.yum install libseccomp-devel-2.3.1-3 
2.gi clong github.com/seccomp/libseccomp-golang
3.cd github.com/seccomp/libseccomp-golang && go build -v
error 
seccomp_internal.go "AUDIT_ARCH_MIPSEL64" undeclared here (not in a function)
const uint32_t C_ARCH_MIPSEL64     = SCMP_ARCH_MIPSEL64;

**Comment by mheon** [comment]
This is properly strange. libseccomp v2.3.1 should have the `SCMP_ARCH_MIPSEL64` define in `seccomp.h`. What Linux distribution are you using, so I can attempt to replicate your environment?

**Comment by guoh1988** [comment]
1.It's "AUDIT_ARCH_MIPSEL64", not "SCMP_ARCH_MIPSEL64.""
2. I can't find define "AUDIT_ARCH_MIPSEL64" in seccomp.h 
/* MIPS64N32 support was merged in 3.15 */
#ifndef AUDIT_ARCH_MIPS64N32
#define AUDIT_ARCH_MIPS64N32	(EM_MIPS|__AUDIT_ARCH_64BIT|\
				 __AUDIT_ARCH_CONVENTION_MIPS64_N32)
#endif
/* MIPSEL64N32 support was merged in 3.15 */
#ifndef AUDIT_ARCH_MIPSEL64N32
#define AUDIT_ARCH_MIPSEL64N32	(EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE|\
				 __AUDIT_ARCH_CONVENTION_MIPS64_N32)
#endif
#define SCMP_ARCH_MIPS		AUDIT_ARCH_MIPS
#define SCMP_ARCH_MIPS64	AUDIT_ARCH_MIPS64
#define SCMP_ARCH_MIPS64N32	AUDIT_ARCH_MIPS64N32
#define SCMP_ARCH_MIPSEL	AUDIT_ARCH_MIPSEL
#define SCMP_ARCH_MIPSEL64	AUDIT_ARCH_MIPSEL64
#define SCMP_ARCH_MIPSEL64N32 AUDIT_ARCH_MIPSEL64N32

**Comment by mheon** [comment]
@guoh1988 Can you give details on your kernel? I'm wondering if it might be a version prior to support for MIPS auditing being merged.

@pcmoore I'm thinking that if AUDIT_ARCH_MIPSEL64 is missing, bad things should be happening with `libseccomp` itself as well -  potentially failures to build? Thoughts?

**Comment by pcmoore** [comment]
Interesting.

The `AUDIT_ARCH_MIPSEL64` definition in /usr/include/linux/audit.h has been around since 2005, see Linux commit 2fd6f58ba6ef ("[AUDIT] Don't allow ptrace to fool auditing, log arch of audited syscalls.").  As a reminder, the first release of libseccomp was back in [2015](https://github.com/seccomp/libseccomp/releases/tag/v0.1.0).

Considering that the `AUDIT_ARCH_MIPSEL64` definition is over 12 years old, I think it is safe to assume that it is defined on the system.  In cases where it is missing it seems like that might be an indicator of an unusual, or non-standard, build environment.

Anyway, on to your question:

> I'm thinking that if AUDIT_ARCH_MIPSEL64 is missing, bad things should be happening with libseccomp itself as well - potentially failures to build? Thoughts?

If `AUDIT_ARCH_MIPSEL64` is not defined, there should be build failures in arch-mips64.c.

**Comment by jiangtao9999** [comment]
There was not MIPSEL64 ,but MIPS64EL in /usr/include/linux/audit.h ......

[root@localhost BUILD]# grep AUDIT_ARCH_MIPSEL64 /usr/include/linux/audit.h
[root@localhost BUILD]# grep AUDIT_ARCH_MIPS64EL /usr/include/linux/audit.h
#define AUDIT_ARCH_MIPS64EL     (EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
#define AUDIT_ARCH_MIPS64EL_N32 (EM_MIPS|__AUDIT_ARCH_ALT|__AUDIT_ARCH_LE)
[root@localhost BUILD]#
[root@localhost BUILD]# rpm -qa "audit*"
audit-libs-devel-2.7.8-1fc27.ls.mips64el
audit-libs-python3-2.7.8-1fc27.ls.mips64el
audit-libs-static-2.7.8-1fc27.ls.mips64el
audit-libs-python-2.7.8-1fc27.ls.mips64el
audit-libs-2.7.8-1fc27.ls.mips64el
audit-2.7.8-1fc27.ls.mips64el
[root@localhost BUILD]#

I'm building fedora 27 on loongson3A ....
Mips is died.....

**Comment by guoh1988** [comment]
[root@localhost linux]# grep AUDIT_ARCH_MIPSEL64 /usr/include/linux/audit.h
#define AUDIT_ARCH_MIPSEL64     (EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
[root@localhost linux]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)
but fedora 21 can't find AUDIT_ARCH_MIPSEL64 loongson3A 
Can you tell me which RPM package audit.h is in

**Comment by jiangtao9999** [comment]
[root@localhost /]# rpm -q --whatprovides  /usr/include/linux/audit.h
kernel-headers-4.4.30-1.fc21.loongson.mips64el
[root@localhost /]#

BUT !

[root@localhost ~]# grep AUDIT_ARCH_MIPS64EL /usr/include/linux/audit.h
[root@localhost ~]# grep AUDIT_ARCH_MIPSEL64 /usr/include/linux/audit.h
#define AUDIT_ARCH_MIPSEL64     (EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
#define AUDIT_ARCH_MIPSEL64N32  (EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE|\
[root@localhost ~]#

Now, It's changed ?
Why ?
O.o

When I updated the kernel packages ?

**Comment by jiangtao9999** [comment]
In that rpm:
http://ftp.loongnix.org/os/loongnix/1.0/kernel/RPMS/Packages/kernel-headers-4.4.30-1.fc21.loongson.mips64el.rpm
audit.h has that:
#define AUDIT_ARCH_MIPSEL64	(EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)

??????? What happend ?????

**Comment by jiangtao9999** [comment]
I known.....

In kernel-headers-3.10.84-17.fc21.loongson.mips64el.rpm 
got in http://ftp.loongnix.org/os/loongnix/1.0/os/Packages/k/kernel-headers-3.10.84-17.fc21.loongson.mips64el.rpm

audit.h have that
#define AUDIT_ARCH_MIPS64EL	(EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)

New kernel is changed it . I was upgraded the kernel in 4 days ago .
I forgot.

**Comment by mheon** [comment]
Sorry for the delayed response it's been a busy week. It seems like this is an issue with the newer kernel you installed, then? Can you file a bug against the kernel package, as missing this define seems like a significant bug

**Comment by jiangtao9999** [comment]
I think it is not an issue . New kernel have the correct define.

But libseccomp defined 
 AUDIT_ARCH_MIPS 
 AUDIT_ARCH_MIPS64 
 AUDIT_ARCH_MIPS64N32 
 AUDIT_ARCH_MIPSEL64N32
Not defined 
 AUDIT_ARCH_MIPSEL
 AUDIT_ARCH_MIPSEL64
in seccomp.h

It is batter to add EL & EL64 .
If kernel does not defined , these define will keep work fine .

--- libseccomp-2.3.2/include/seccomp.h.in.orig  2017-12-11 15:10:06.000000000 +0000
+++ libseccomp-2.3.2/include/seccomp.h.in       2017-12-11 15:11:18.000000000 +0000
@@ -149,9 +149,15 @@
 #ifndef AUDIT_ARCH_MIPS
 #define AUDIT_ARCH_MIPS                (EM_MIPS)
 #endif
+#ifndef AUDIT_ARCH_MIPSEL
+#define AUDIT_ARCH_MIPSEL      (EM_MIPS|__AUDIT_ARCH_LE)
+#endif
 #ifndef AUDIT_ARCH_MIPS64
 #define AUDIT_ARCH_MIPS64      (EM_MIPS|__AUDIT_ARCH_64BIT)
 #endif
+#ifndef AUDIT_ARCH_MIPSEL64
+#define AUDIT_ARCH_MIPSEL64     (EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
+#endif
 /* MIPS64N32 support was merged in 3.15 */
 #ifndef AUDIT_ARCH_MIPS64N32
 #define AUDIT_ARCH_MIPS64N32   (EM_MIPS|__AUDIT_ARCH_64BIT|\

**Comment by jiangtao9999** [comment]
`--- libseccomp-2.3.2/include/seccomp.h.in.orig	2017-12-11 15:10:06.000000000 +0000
+++ libseccomp-2.3.2/include/seccomp.h.in	2017-12-11 15:11:18.000000000 +0000
@@ -149,9 +149,15 @@
 #ifndef AUDIT_ARCH_MIPS
 #define AUDIT_ARCH_MIPS		(EM_MIPS)
 #endif
+#ifndef AUDIT_ARCH_MIPSEL
+#define AUDIT_ARCH_MIPSEL      (EM_MIPS|__AUDIT_ARCH_LE)
+#endif
 #ifndef AUDIT_ARCH_MIPS64
 #define AUDIT_ARCH_MIPS64	(EM_MIPS|__AUDIT_ARCH_64BIT)
 #endif
+#ifndef AUDIT_ARCH_MIPSEL64
+#define AUDIT_ARCH_MIPSEL64     (EM_MIPS|__AUDIT_ARCH_64BIT|__AUDIT_ARCH_LE)
+#endif
 /* MIPS64N32 support was merged in 3.15 */
 #ifndef AUDIT_ARCH_MIPS64N32
 #define AUDIT_ARCH_MIPS64N32	(EM_MIPS|__AUDIT_ARCH_64BIT|\
`

**Comment by pcmoore** [comment]
Two thoughts:

1. Do these older kernels even provide seccomp-bpf support?  You mention EL64 which I assume is CENTOS/RHEL-6.4 and seccomp-bpf is definitely not supported there.

2. This isn't specific to the libseccomp-golang bindings is it?  Should this be entered against the main libseccomp repository?  Although see question 1 before reassigning to libseccomp.
