### ISSUE TITLE
Q: how to use string condition in AddRuleConditional()

### ISSUE THREAD

**Issue by Hannnnnn** [seccomp/libseccomp-golang#34]
Hello,
I was trying to add a string condition in AddRuleConditional(). ( allow a system call if path parameter is matched.)
However I found it is tricky. 
I ever use C code in Golang to cover string into uint64 but it does not work.
I wonder what is the correct way to use string condition ? 
Thank you.

**Comment by pcmoore** [comment]
Hi @Hannnnnn,

Unfortunately the seccomp code in the kernel is not capable of dereferencing pointers, which makes it impossible to do string comparisons with seccomp.  I'm going to close this out as there is nothing we can do in userspace to fix this.
