### ISSUE TITLE
Q: release tagging

### ISSUE THREAD

**Issue by jessfraz** [seccomp/libseccomp-golang#4]
it looks nicer when we vendor into docker/docker, no rush just wondering :)

**Comment by mheon** [comment]
Planning on cutting a new release of the bindings soon, to coincide with a planned release of libseccomp itself --- can probably tag the bindings once that happens. We do need to figure out a version format for the bindings, though - @pcmoore, thoughts on that?

**Comment by pcmoore** [comment]
I'm focusing on getting some things fixed in the main libseccomp library first so we can get that release out the door.  See here: https://groups.google.com/forum/#!topic/libseccomp/v6Sx3rObG5A

My initial thinking is to keep the version format/numbering the same as the main libseccomp release to keep things consistent - any objections?

**Comment by mheon** [comment]
Sounds good to me, though there might eventually be need for another version field if we need multiple versions of the bindings for a single library version (if, say, we had a bug in the 2.2.3 bindings and needed a new bindings release, I'd want to distinguish them as 2.2.3.1 or similar).

**Comment by pcmoore** [comment]
Yep, sounds good to me.

**Comment by pcmoore** [comment]
@mheon I've given this some more thought and wonder if matching the main libseccomp version numbers might be a mistake.  As you pointed out, it seems very likely that we will need to iterate the two packages independently of each other.  Any idea what other golang bindings do?

**Comment by pcmoore** [comment]
@jessfraz Since you're the reporter here, any opinions on how best to handle versioning of golang projects such as this which are just bindings to libraries written in other languages?  How do most projects handle this today: independent version numbers or sync with the main project?

**Comment by mheon** [comment]
Sorry for the delay here, I'll try and find some time to take a look into this today.

**Comment by pcmoore** [comment]
No worries, it really is just a question regarding the version numbers for the golang bindings.  We've got most of the pressing issues sorted such that I'm comfortable tagging a release, I'm just waffling a bit on the most golang-y approach.

**Comment by thorduri** [comment]
@pcmoore 

> I'm just waffling a bit on the most golang-y approach. 

Can you expand on this this point ?

My two cents:
Matching the `seccomp` versions feels strange off the top of my head as the bindings support multiple versions of `seccomp` -- and if the bindings need a bump (for whatever reason) it can
easily become messy.

**Comment by pcmoore** [comment]
To be clear, when I say waffling, I mean waffling on the version number for the golang bindings (see my above comments).  I would prefer to stay consistent with other golang bindings (the reason for my "golang-y" comment above).

**Comment by mheon** [comment]
After some research, it appears that the majority of bindings version themselves independently of the libraries themselves, though there is a sizable fraction that do tag things relative to the main library like we were doing previously.

**Comment by pcmoore** [comment]
@mheon Thanks for the follow-up; it looks like independent versioning is the Right Thing To Do.  Now, the next question: with the golang bindings in use for some time now, how happy are you with the API?  Are you comfortable enough to tag this as v1.0.0, or do you think we should stick with something less than 1.0 to give us some wiggle room in case the binding's API needs to change?

**Comment by mheon** [comment]
I think we have one remaining sticking point in the API, that being the suggestion from @thorduri to make TSync default and remove the set function associated with it. I don't think we should tag a 1.0 without getting that sorted. Everything else is unlikely to change significantly, though.

**Comment by thorduri** [comment]
@pcmoore, @mheon tagging v1.0.0 after resolving #18 (I can update it to remove the functions, rather then leaving the stubs) would make me a happy camper indeed.

It *will* set the minimum required version to 2.2.0 -- but I think usage of the bindings is inherently dangerous without it, so should not be supported.

**Comment by pcmoore** [comment]
Thanks for the input everyone.

I'm going to go ahead and tag the current code as v0.9.0 simply so we have a tag for developers to reference and we can work towards getting everything ready/reviewed for a v1.0.0 release.

**Comment by pcmoore** [comment]
Closing this with commit e3496e3a417d1dc9ecdceca5af2513271fed37a0 and tag v0.9.0.
