### ISSUE TITLE
RFE: evaluate README.md

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp-golang#40]
Compare the golang binding's README.md with the main libseccomp README.md to see if any additional edits should be made to the golang's README.md.  Whenever possible we should try to remove redundancy between the two, using the main libseccomp README.md as the main reference.

**Comment by kolyshkin** [comment]
This is partially addressed by #69; frankly, I don't know what else to remove from there. An introductory paragraph about libseccomp seems very relevant and provide needed keywords for search engines. Other than that, it's all links to the docs.

**Comment by pcmoore** [comment]
I think @kolyshkin's updates are enough to close this out, if anything remains we can address it via a new issue.  Thanks for your help @kolyshkin!
