### ISSUE TITLE
RFE: Add support for SCMP_FLTATR_CTL_SSB

### ISSUE THREAD

**Issue by KentaTada** [seccomp/libseccomp-golang#47]
runc needs to use SCMP_FLTATR_CTL_SSB in https://github.com/opencontainers/runc/issues/2430 to make bytecode interpreters including Ruby and Python faster when users can disable mitigation.

**Comment by KentaTada** [comment]
`SCMP_FLTATR_CTL_SSB` was not included in the release of libseccomp v2.4.3.
So, we need to wait for the next release of libseccomp at first.

**Comment by pcmoore** [comment]
Adding the `pending/libseccomp` label to indicate this is dependent on a new libseccomp release (v2.5.0).

**Comment by KentaTada** [comment]
I'll try to implement this feature if this priority is low.

**Comment by pcmoore** [comment]
Thanks @KentaTada, help is always appreciated.

FWIW, now that core libseccomp v2.5.0 has been released @drakenclimber and I are going to try and spend some more time cleaning up the golang bindings.

**Comment by KentaTada** [comment]
@pcmoore  Thanks!
I created https://github.com/seccomp/libseccomp-golang/pull/51

**Comment by KentaTada** [comment]
https://github.com/seccomp/libseccomp-golang/pull/51 has been already merged.
