### ISSUE TITLE
RFE: add CHANGELOG and SUBMITTING_PATCHES

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp-golang#5]
Additional documentation to help guide the libseccomp golang bindings, borrow heavily from the main project.

**Comment by mheon** [comment]
We should also consider adding some simple documentation and examples to the README, as sort of a "Getting Started Guide" for the bindings. I can definitely see about adding this and a changelog; SUBMITTING_PATCHES sounds like it could reasonably be copied directly from the main repository

**Comment by pcmoore** [comment]
Yes, I'm going to be copying the SUBMITTING_PATCHES file from the main repo and making few, if any changes.  I'll also create the CHANGELOG in the same format as the main repo, starting with this upcoming release.

As for README additions, if you want to add some text, that would be great!  Feel free to add another issue specifically for that if you want to track it on Github.

**Comment by pcmoore** [comment]
Initial SUBMITTING_PATCHES file included via e3fd4d5f3aa40536a0445fe20f81a69e26a50144.

**Comment by pcmoore** [comment]
Initial CHANGELOG file included via fb54829376a9be85613c7a184695f21275a3f668.
