### ISSUE TITLE
Q: cut a new release

### ISSUE THREAD

**Issue by saschagrunert** [seccomp/libseccomp-golang#55]
Hey maintainers :wave:, may I ask you to cut a new release that we can utilize the new types in the repository?

**Comment by pcmoore** [comment]
FYI, we are tracking the releases with GH milestones, the next release is being tracked with the milestone below:
* https://github.com/seccomp/libseccomp-golang/milestone/3

The quickest way to get a new release out would be to take one of those issues and provide a PR, or take one of the existing PRs and help review it.  Although in the interest of full-disclosure the maintainers are pretty busy right now getting the next maintenance releases of the main libseccomp repo out the door (we've got both v2.4.x and v2.5.x releases pending).

**Comment by pcmoore** [comment]
Since this was a request/question and it was answered above, I'm going to go ahead and close this issue.

**Comment by pcmoore** [comment]
No problem, sorry it wasn't quite the answer you were looking for, but at least it should provide a roadmap and an easy way to check the status.

**Comment by saschagrunert** [comment]
> No problem, sorry it wasn't quite the answer you were looking for, but at least it should provide a roadmap and an easy way to check the status.

Oh I'm also happy to contribute to this project as well. I'll triage the open milestone issues in the next weeks :+1:

**Comment by drakenclimber** [comment]
My apologies as well.  Unfortunately the libseccomp-golang project continues to be on my I'll-get-to-that-soon list :(.

Any help you can offer would be greatly appreciated.  Thanks in advance!
