### ISSUE TITLE
RFE: add seccomp notifier support

### ISSUE THREAD

**Issue by saschagrunert** [seccomp/libseccomp-golang#56]
I saw that libseccomp 2.5.0 added 6 new notifier APIs:
```c
int seccomp_notify_alloc(struct seccomp_notif **req, struct seccomp_notif_resp **resp);
void seccomp_notify_free(struct seccomp_notif *req, struct seccomp_notif_resp *resp);
int seccomp_notify_receive(int fd, struct seccomp_notif *req);
int seccomp_notify_respond(int fd, struct seccomp_notif_resp *resp);
int seccomp_notify_id_valid(int fd, uint64_t id);
int seccomp_notify_fd(const scmp_filter_ctx ctx);
```
Referring to https://github.com/seccomp/libseccomp-golang/issues/37, I think it would make sense to add the binding and structures to this project, too. I could take care of the implementation/testing if you want. WDYT?

**Comment by pcmoore** [comment]
PRs are always welcome :)

**Comment by AkihiroSuda** [comment]
https://github.com/seccomp/libseccomp-golang/commit/78c92cbc6966350c27f365890f4cd47ebb934594 was merged, can we get v0.9.2 soon? 🙏

**Comment by pcmoore** [comment]
> [78c92cb](https://github.com/seccomp/libseccomp-golang/commit/78c92cbc6966350c27f365890f4cd47ebb934594) was merged, can we get v0.9.2 soon?

When all of the items in the v0.9.2 milestone are resolved we will tag a new release.
* https://github.com/seccomp/libseccomp-golang/milestone/3

**Comment by pcmoore** [comment]
As was pointed out above, this issue should now be resolved; closing this issue.

**Comment by edelkind** [comment]
Before v0.9.2 comes out, is there a good reason that "Notif" is used everywhere instead of "Notify"?  It only saves one letter, and it plays tricks on one's mind while using it.  It also doesn't seem very "go"-esque.  @pcmoore - I'm happy to make this change if it's deemed acceptable.
