### ISSUE TITLE
BUG: look into replacing Travis CI with GitHub actions

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp-golang#60]
There are plenty of articles on this, but see The Register article below for some background on this issue:

* https://www.theregister.com/2020/11/02/travis_ci_pricng

With Travis CI becoming potentially unreliable for libseccomp, we should investigate moving out CI testing to GitHub actions:

* https://docs.github.com/en/free-pro-team@latest/actions

**Comment by drakenclimber** [comment]
Good find.  I have been running into issues with libcgroup running on TravisCI as well.  I'm very interested in this issue.

**Comment by pcmoore** [comment]
Yes, I think most folks are starting to see problems with Travis CI.  I *think* we should be able to move to GH actions without too much problem but I haven't looked just yet, I may start playing with it this weekend depending on how things go around here.

With the main libseccomp v2.5.x releases stabilizing, we also need to start working through some of the issue/PR backlog here in the Go bindings.

**Comment by kolyshkin** [comment]
PTAL #65.

**Comment by drakenclimber** [comment]
Merged via commit https://github.com/seccomp/libseccomp-golang/commit/e5b1e63fb25d704a39b9079d758824587f31a5f2 and others.  CI is passing [here](https://github.com/seccomp/libseccomp-golang/runs/3570811836).
