### ISSUE TITLE
BUG: Replace TravisCI Badge with Github Actions Badge

### ISSUE THREAD

**Issue by drakenclimber** [seccomp/libseccomp-golang#68]

**Comment by kolyshkin** [comment]
This should show the latest status for main branch:
[![validate](https://github.com/seccomp/libseccomp-golang/actions/workflows/validate.yml/badge.svg)](https://github.com/seccomp/libseccomp-golang/actions/workflows/validate.yml) [![test](https://github.com/seccomp/libseccomp-golang/actions/workflows/test.yml/badge.svg)](https://github.com/seccomp/libseccomp-golang/actions/workflows/test.yml)

**Comment by pcmoore** [comment]
Closing this out as it is resolved.
