### ISSUE TITLE
RFE: add support for MIPS/PPC/s390 to the golang bindings

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp-golang#7]
As requested by Phil Estes along with a patch:

 * https://groups.google.com/forum/#!topic/libseccomp/JXRvNsdGGPw

**Comment by estesp** [comment]
Now that it looks like the main C lib is up to v2.3.1, is there any chance some of these changes can get into the Go bindings and a release can be cut?  Thanks!

**Comment by pcmoore** [comment]
Merged in 60c9953736798c4a04e90d0f3da2f933d44fd4c4, thanks for your patience!

**Comment by michael-holzheu** [comment]
I am no expert for libseccomp-golang, but aren't changes for `seccomp_internal.go` missing to be complete?

Something like the following (untested) patch: 2e378814b62dc4af74259914a29c5621bb91c744

**Comment by michael-holzheu** [comment]
In case I am right, for your convenience, I created PR #10.

**Comment by michael-holzheu** [comment]
ping @tophj-ibm

**Comment by pcmoore** [comment]
PR #10 merged via 32f571b70023028bd57d9288c20efbcb237f3ce0.
