### ISSUE TITLE
Q: please cut a 0.9.1.1 release with RISC-V support

### ISSUE THREAD

**Issue by xnox** [seccomp/libseccomp-golang#76]
v0.9.2 milestore is not ready yet, but there is riscv64 support in master, can you please bump v0.9.2 milestone work to v0.9.3 and release v0.9.2 already as is? or like tag and release v0.9.1.1? it would help a lot with riscv64 bootstrapping.

**Comment by pcmoore** [comment]
Hi @xnox,

I understand that RISC-V support is very important to you, but we are making good progress towards the v0.9.2 release and I would rather see our efforts go towards finishing that than making a v0.9.1.1 release.
